### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by weigeloveu** [RoyalFlyBy/ChaturbateWatcher#1]
![TIM截图20200225095929](https://user-images.githubusercontent.com/19830500/75208104-96dd3d00-57b5-11ea-8a95-b8a934904412.png)
![TIM截图20200225095901](https://user-images.githubusercontent.com/19830500/75208117-9f357800-57b5-11ea-9bce-62a31fae5460.png)
run a while it became the black screen

**Comment by RoyalFlyBy** [comment]
That issue is indeed very annoying, no idea how to work around it for now however I did find by pressing ENTER (in the cmd, I usually press once but sometimes twice) it turns normal again.

Only happens on Windows 10 by my knowledge.

Actually after some quick testing it seems to happen explicitly by clicking the cmd window multiple times, ENTER key still fixes it though. Maybe I will try to fix it but for now the issue is rooted in code that I did not write.

**Comment by weigeloveu** [comment]
thanks for reply,another question is how to manual start a record?must it wait email?
i tried to email to myselfe but seems doesnt work,im using outlook

**Comment by ghost** [comment]
Sorry **@RoyalFlyBy**, but You said ...

> Only happens on Windows 10 by my knowledge.

I'm about to change my PC by upgrading from Windows 7 to Windows 10: will there be any problems with the new operating system? I confess that Your sentence _has alarmed me_: just press ENTER and that's it, if this bug occurs🤔?

**Comment by RoyalFlyBy** [comment]
@weigeloveu 
No problem.
For manual download use 
https://github.com/RoyalFlyBy/ChaturbateDownloader

However I do have to say that it doesn't respond to any emails that isn't explicitly from Chaturbate's notification service.

If you suspect a bug please enable debugging in settings.json by changing ```false``` to ```true``` where it says ```debugging``` as it will show more information that can help

I suppose I could add an option for it to also respond to email sent by other accounts.

**Comment by RoyalFlyBy** [comment]
@Simon01-dummy 
There is no need to worry, I myself test my programs explicitly on Windows 10 so they will always be checked to work

Though if you ever click on the window where this program is running and it is black with no text as expected then press ENTER to FIX it as the program is still working in the background but somewhere there was a glitch with communication between the CMD from Windows and the UI library of the program i used

ENTER fixes it😀

**Comment by weigeloveu** [comment]
another problem is it cant see the head lines of program,it keep pops.
![InstantGif_2020 02 27-18 28](https://user-images.githubusercontent.com/19830500/75436161-11ad8000-598f-11ea-97ab-8b3e70c8a2aa.gif)

**Comment by RoyalFlyBy** [comment]
That is normal for now, the only solution to that would be showing less data which is not something that I can't get behind as of right now.

The popping happens when it updates with new data. (each second)

Maybe in the future I will work around having a terminal UI all together but for now I don't know what could be a viable replacement.
